import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navigation from "@/components/navigation";

import { Toaster } from "@/components/ui/sonner";
import NavigationDesktop from "@/components/navigation-desktop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "School Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html
        lang="en"
        className={`styled-scrollbar ${geistSans.variable} ${geistMono.variable} `}
        suppressHydrationWarning
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable}   h-screen flex flex-col gap-8 items-center  antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            <Navigation />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
